version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: dptzy/nestapp:1.0.0
    build:
      context: .
    ports:
      - '9000:9000'
    environment:
      - DB_TYPE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=Piito#1911
      - PG_DB=test_local_db
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Piito#1911
      POSTGRES_DB: test_local_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
